ENT.Type = 'anim'
ENT.Type = "ai"
ENT.Base = 'base_gmodentity'
ENT.Contact = ''
ENT.Purpose = ''
ENT.Instructions = ''
ENT.PrintName = "Dummy(WIP)"
ENT.Author= "Kitsune"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.Category = 'Kitsune'
ENT.RenderGroup = RENDERGROUP_BOTH
